### ISSUE TITLE
How much to move?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2plot#1]
@mattfidler , As I'm creating this by extracting the plotting functions from nlmixr2, I'm curious of your opinion:  How much should we move?

My initial thought was that I should move everything that does plotting from `nlmixr2` into this package as the first pass.  My goal in that was that anything that was ggplot2-related outside of vignettes should come here.  And, it should be extensive enough that `ggplot2` could change from being an import (required for running the package) to a suggested package (only required for vignettes).

That was a bit more extensive than I initially thought it would be, so I have a few questions to confirm with you:

* Complete files:
    * the nlmixr2/R/plot.R is moved (that seems pretty simple to do)
* Complete functions
    * `plot.nlmixr2AugPred`
    * `plot.nlmixr2Sim`
    * `plot.saemFit`

Harder questions:

* Should all of `vpc` support move here?  (Since, the main point of a vpc is plotting, but there is the challenge that it also includes simulation and summary statistic generation.)
* `bootstrapFit` has a `plotHist` argument.  Should it somehow move here (for example, make the argument defunct and move it here)?

**Comment by billdenney** [comment]
Similar to the above, should the following move from rxode2 to here:

* `rxTheme()`?
* Generally, all of rxode2/R/plot.R
* geom_amt, geom_cens, stat_cens, and stat_amt?

**Comment by billdenney** [comment]
As I'm thinking a bit more about it, perhaps VPC fits best in the "support" package.  Maybe call it nlmixr2extra to align with some other packages' "extra" package names?

**Comment by mattfidler** [comment]
> Similar to the above, should the following move from rxode2 to here:
I would only want to move the following functions from `rxode2`:

 * `geom_amt`, `geom_cens`, `stat_cens`, and `stat_amt`?

`rxode2` should stand alone.  If you move it to a separate package all of these plot functions are not available without an additional dependency.  Since the dependency count is too large as it is, keep the rest there.

**Comment by mattfidler** [comment]
However `bootstrapFit` should be left alone right now.  The plot requires a different set of models to be evaluated and it definitely not a plot-only item for now.

**Comment by billdenney** [comment]
It's all moved, now.
