### ISSUE TITLE
Simplify censoring text?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2plot#19]
Should we simplify the text used for censoring?  Specifically, could the data always indicate if it is left or right censored and drop the column if it doesn't exist (rather than having different cases for left and right censoring).

https://github.com/nlmixr2/nlmixr2plot/blob/094a0b1e74e910f9b6d97b337bd422d8b5882eb1/R/plot.nlmixr2.R#L16-L28

**Comment by mattfidler** [comment]
It is already dropped when censoring is not present.

The "Censored data" is more understandable to people than "Right" or "Left", but I suppose we could align the terms.  I thought it was easier to read for a majority of people.

**Comment by mattfidler** [comment]
I personally have to think about right vs left myself.

**Comment by billdenney** [comment]
If it seems like it'd make people think about it more without a benefit of clarity, no need to change it.

**Comment by mattfidler** [comment]
Sounds fine to me.
