### ISSUE TITLE
Preserve the `nlmixr2.save` option handling?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2plot#2]
@mattfidler , In `plot.nlmixr2Sim`, there is an undocumented option where it will look at the `nlmixr2.save` option and save the plot if it is set.

I've not used that functionality, so I don't understand its value.  But, since it is undocumented, and separate from the main plotting functionality, would it be okay to remove that feature?

**Comment by mattfidler** [comment]
The simulation has changed and it is unclear what needs to be happening here.

**Comment by billdenney** [comment]
Fixed in nlmixr2est
