### ISSUE TITLE
Import nlmixr2est

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2plot#3]
When the renaming from nlmixr2 to nlmixr2est is complete, import nlmixr2est instead of nlmixr2.

**Comment by mattfidler** [comment]
Should it depend on anything?  It don't think it needs to...

**Comment by billdenney** [comment]
For some of the plotting, extra work can be done such as a call to `nlmixr2::nlmixr()` or `nlmixr2::bootstrap()` (those are from memory as I'm not at the computer now).

The right answer may be to move that code back to `nlmixr2est` or to make it a suggested dependency with `requireNamespace()`.

**Comment by mattfidler** [comment]
Sorry I think I was confused.  You mean to import nlmixr2est.  It just had to make `nlmixr2data` a `Depends` because otherwise you don't see the data.  

This is fine..

**Comment by billdenney** [comment]
Ah, yes.  I edited the above comments to all say import instead of depend now.

**Comment by mattfidler** [comment]
Done.
