### ISSUE TITLE
No tag for latest CRAN release

### ISSUE THREAD

**Issue by rikardn** [nlmixr2/nlmixr2plot#34]
There is no tag for the version on CRAN.

**Comment by billdenney** [comment]
I think that should be tagged on 3332dc8fa1c564d459063e0185da0aff94bcfdbe

**Comment by rikardn** [comment]
Thanks @billdenney and sorry for being terse in my initial post. I was going through the traceability of the source code repositories and the CRAN releases of all (internal) dependencies of nlmixr2 and rxode2 and found that most packages had really great version tagging except for a few. Thanks for considering this.

**Comment by mattfidler** [comment]
Fixed.  Also for the prior release.

**Comment by rikardn** [comment]
Thanks!
